services:
  opusclassical-clojure:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000
    networks:
      - dokploy-network
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    labels:
      - traefik.enable=true
      - traefik.http.routers.opusclassicalclojure.rule=Host(`clojure.opusclassical.net`)
      - traefik.http.services.opusclassicalclojure.loadbalancer.server.port=3000
      - traefik.http.routers.opusclassicalclojure.entrypoints=websecure
      - traefik.http.routers.opusclassicalclojure.tls.certResolver=letsencrypt

networks:
  dokploy-network:
    external: true
