name: Clojure CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "23"

      - name: Install Leiningen
        uses: DeLaGuardo/setup-clojure@12.6
        with:
          lein: latest

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install dependencies
        run: lein deps

      - name: Run tests
        run: lein test
